variables:
  ProvisioningRequired:  $(Parameters.ProvisioningRequired)
  ConfigurationRequired:  $(Parameters.ConfigurationRequired)
  DeploymentRequired:  $(Parameters.DeploymentRequired)
  Parameters.appName: $(Parameters.launchpadAppName)
  Parameters.deploymentName: $(Build.DefinitionName)
  
stages:
- stage: 'release'
  displayName: 'Release'

  jobs:
  - job: 'Resource_Provisioning'
    variables:
      Build.SyncSources: false
    pool:
     name: Hosted VS2017
    steps:
    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          # Write your powershell commands here.
          Write-Host "Resource_Provisioning"
    
  - job: 'Deployment'
    variables:
      Build.SyncSources: eq(variables.DeploymentRequired,true)
    dependsOn: Resource_Provisioning
    pool:
      name: Hosted VS2017
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your powershell commands here.
            Write-Host "Deployment"

  - job: 'Configuration'
    variables:
      Build.SyncSources: eq(variables.ConfigurationRequired,true)
    dependsOn: [Resource_Provisioning, Deployment]
    pool:
        name: Hosted VS2017
    steps:
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            # Write your powershell commands here.
            Write-Host "Configuration"